{
  "formatVersion": "1.1",
  "component": {
    "group": "github.com.gengyoubo",
    "module": "ManaitaPlusGeneral",
    "version": "2.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ManaitaPlusGeneral-2.3.2-1.20.1-forge.jar",
          "url": "ManaitaPlusGeneral-2.3.2-1.20.1-forge.jar",
          "size": 540467,
          "sha512": "a422b7ad49f84a903ee25525dc49e5a39ee2e14859bc1347b13c05fd691dd22d7926c8f6c6baa8b1c929fece63c22ba9d94932d2856f3392b8c37fb07f1c3b4f",
          "sha256": "de9cddba0ebfc0ad8c1c7b338016d00d313b88be5d2d68abc459fb0330f6b8c1",
          "sha1": "09d3d0e6ffbaaaa9822f58406c454e78cb3d1441",
          "md5": "b4ff4eb7436bfaa4eaad1315073c4604"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "applied-energistics-2-223794",
          "version": {
            "strictly": "7148487_mapped_official_1.20.1",
            "requires": "7148487_mapped_official_1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "guideme-1173950",
          "version": {
            "strictly": "7127447_mapped_official_1.20.1",
            "requires": "7127447_mapped_official_1.20.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.2.19_mapped_official_1.20.1_at_c4c149b86af210a1f2546a973658ab5d4ce1f727"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "strictly": "15.20.0.130_mapped_official_1.20.1",
            "requires": "15.20.0.130_mapped_official_1.20.1"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-forge",
          "version": {
            "strictly": "5.14.1+1.20.1_mapped_official_1.20.1",
            "requires": "5.14.1+1.20.1_mapped_official_1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "ManaitaPlusGeneral-2.3.2-1.20.1-forge.jar",
          "url": "ManaitaPlusGeneral-2.3.2-1.20.1-forge.jar",
          "size": 540467,
          "sha512": "a422b7ad49f84a903ee25525dc49e5a39ee2e14859bc1347b13c05fd691dd22d7926c8f6c6baa8b1c929fece63c22ba9d94932d2856f3392b8c37fb07f1c3b4f",
          "sha256": "de9cddba0ebfc0ad8c1c7b338016d00d313b88be5d2d68abc459fb0330f6b8c1",
          "sha1": "09d3d0e6ffbaaaa9822f58406c454e78cb3d1441",
          "md5": "b4ff4eb7436bfaa4eaad1315073c4604"
        }
      ]
    }
  ]
}
